name: Automate Deploy
on:
  push:
    branches:
      - deploy
jobs:
  automate-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            set -e
            trap 'echo "‚ùå Deployment failed!" && exit 1' ERR
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd /root/idg-devops-practice
            git reset --hard HEAD
            git checkout deploy
            git pull origin deploy
            pm2 reload index
